

try:
    prin
except Exception as e:
    print("Erreur : %s" % e)